// Company data — from state.json generated by new-company
export interface SkillEntry {
  id: string;
  category: string;
  label: string;
  installed: boolean;
  custom: boolean;
}

export interface CompanyInfo {
  name: string;
  slug: string;
  tagline: string;
  profile: string;
  language: string;
}

export interface DashboardState {
  generated_at: string;
  company: CompanyInfo;
  skills: SkillEntry[];
  wiki: { projects: string[]; areas: string[] };
  kpis: string[];
  goal_90d: string;
  ws_url: string;
}

// Live state types — matches squad runner WsMessage protocol
export interface AgentDesk {
  col: number;
  row: number;
}

export type AgentStatus =
  | "idle"
  | "working"
  | "delivering"
  | "done"
  | "checkpoint";

export interface Agent {
  id: string;
  name: string;
  icon: string;
  status: AgentStatus;
  gender?: "male" | "female";
  desk: AgentDesk;
}

export interface Handoff {
  from: string;
  to: string;
  message: string;
  completedAt: string;
}

export type SquadStatus =
  | "idle"
  | "running"
  | "completed"
  | "checkpoint";

export interface SquadState {
  squad: string;
  status: SquadStatus;
  step: {
    current: number;
    total: number;
    label: string;
  };
  agents: Agent[];
  handoff: Handoff | null;
  startedAt: string | null;
  updatedAt: string;
}

export interface SquadInfo {
  code: string;
  name: string;
  description: string;
  icon: string;
  agents: string[];
}

export type WsMessage =
  | { type: "SNAPSHOT"; squads: SquadInfo[]; activeStates: Record<string, SquadState> }
  | { type: "SQUAD_UPDATE"; squad: string; state: SquadState }
  | { type: "SQUAD_INACTIVE"; squad: string };
